export interface Service {
  id: string;
  category: "Advanced Skin Care" | "Hair Restoration" | "Permanent Makeup" | "Facial Plastic Surgery";
  title: string;
  shortDescription: string;
  detailedDescription?: string;
  features?: string[];
  price: string;
  duration?: string;
  recovery?: string;
  image: string;
  popular?: boolean;
}

export const servicesData: Service[] = [
  // Advanced Skin Care
  {
    id: "acne-treatment",
    category: "Advanced Skin Care",
    title: "Advanced Acne Treatment",
    shortDescription: "Clear, smooth skin with medical-grade chemical peels.",
    detailedDescription: "Our advanced chemical peels penetrate deep to unclog pores, reduce inflammation, and prevent future breakouts. Customized formulations target your specific acne type for lasting results.",
    features: ["Deep pore cleansing", "Inflammation reduction", "Breakout prevention", "Custom formulation"],
    price: "Starting from ₹1,000",
    duration: "30-45 minutes",
    recovery: "2-3 days",
    image: "/placeholder.svg",
    popular: true,
  },
  {
    id: "hydrafacial",
    category: "Advanced Skin Care",
    title: "HydraFacial Treatment",
    shortDescription: "Instantly revitalize dull, tired skin with deep hydration.",
    detailedDescription: "Experience the ultimate 3-in-1 treatment that cleanses, extracts, and hydrates. HydraFacial delivers immediate glow and long-term skin health benefits with zero downtime.",
    features: ["3-in-1 treatment", "Immediate glow", "No downtime", "Long-term benefits"],
    price: "₹3,000",
    duration: "45 minutes",
    recovery: "None",
    image: "/placeholder.svg",
    popular: true,
  },
  {
    id: "brightening-detan",
    category: "Advanced Skin Care",
    title: "Brightening & De-tan Solutions",
    shortDescription: "Restore your natural radiance with advanced peels and laser technology.",
    detailedDescription: "Combat pigmentation, sun damage, and uneven tone with our combination approach. Chemical peels and laser treatments work synergistically for luminous, even-toned skin.",
    features: ["Pigmentation reduction", "Sun damage repair", "Even skin tone", "Advanced peels + laser"],
    price: "Starting from ₹1,500",
    duration: "60 minutes",
    recovery: "3-5 days",
    image: "/placeholder.svg",
  },
  {
    id: "scar-pore-repair",
    category: "Advanced Skin Care",
    title: "Scar Reduction & Pore Refinement",
    shortDescription: "Smooth texture and minimize scars with regenerative treatments.",
    detailedDescription: "PRP, GFC, Vampire Facial, and MNRF stimulate collagen production to fade scars, tighten pores, and improve overall skin texture. Natural healing for natural-looking results.",
    features: ["Collagen stimulation", "Scar fading", "Pore tightening", "Natural healing"],
    price: "Starting from ₹3,000",
    duration: "60 minutes",
    recovery: "1-2 days",
    image: "/placeholder.svg",
    popular: true,
  },
  {
    id: "non-surgical-facelift",
    category: "Advanced Skin Care",
    title: "Non-Surgical Face Lifting",
    shortDescription: "Tighten and contour without surgery using HIFU and RF technology.",
    detailedDescription: "High-Intensity Focused Ultrasound and Radiofrequency treatments lift sagging skin, reduce facial fat, and redefine your contours. See visible tightening with progressive improvements over 3-6 months.",
    features: ["HIFU technology", "RF skin tightening", "Non-invasive", "Progressive results"],
    price: "Starting from ₹15,000",
    duration: "45-60 minutes",
    recovery: "None",
    image: "/placeholder.svg",
  },
  {
    id: "wart-removal",
    category: "Advanced Skin Care",
    title: "Medical Wart Removal",
    shortDescription: "Safe, effective removal of warts with minimal scarring.",
    detailedDescription: "Advanced laser and cryotherapy techniques safely remove warts without leaving scars or marks. Permanent removal with minimal discomfort and quick recovery.",
    features: ["Laser removal", "Cryotherapy", "Minimal scarring", "Quick recovery"],
    price: "Starting from ₹5,000",
    duration: "15-30 minutes",
    recovery: "3-5 days",
    image: "/placeholder.svg",
  },
  {
    id: "laser-hair-removal",
    category: "Advanced Skin Care",
    title: "Permanent Hair Reduction",
    shortDescription: "Painless, lasting smoothness with advanced laser technology.",
    detailedDescription: "Say goodbye to razors and waxing. Our FDA-approved lasers target hair follicles for permanent reduction across all skin types with minimal discomfort.",
    features: ["FDA-approved lasers", "All skin types", "Minimal discomfort", "Permanent reduction"],
    price: "Starting from ₹15,000",
    duration: "30-45 minutes",
    recovery: "None",
    image: "/placeholder.svg",
  },

  // Hair Restoration
  {
    id: "hair-growth-treatment",
    category: "Hair Restoration",
    title: "Non-Surgical Hair Restoration",
    shortDescription: "Stimulate natural hair growth with PRP, GFC, and QR678.",
    detailedDescription: "Advanced growth factors and stem cell therapies rejuvenate dormant follicles, increase density, and strengthen existing hair. Visible results in 3-4 sessions.",
    features: ["PRP therapy", "GFC treatment", "QR678 injection", "Follicle rejuvenation"],
    price: "Starting from ₹3,000",
    duration: "30-45 minutes",
    recovery: "None",
    image: "/placeholder.svg",
  },
  {
    id: "hair-transplant",
    category: "Hair Restoration",
    title: "Surgical Hair Transplant",
    shortDescription: "Permanent solution for hair loss with natural-looking results.",
    detailedDescription: "FUE and FUT techniques restore your hairline with precision. Our surgeons create density and design that looks completely natural and lasts a lifetime.",
    features: ["FUE technique", "FUT technique", "Lifetime results", "Natural design"],
    price: "Starting from ₹50,000",
    duration: "6-8 hours",
    recovery: "7-14 days",
    image: "/placeholder.svg",
  },

  // Permanent Makeup
  {
    id: "permanent-lip-tinting",
    category: "Permanent Makeup",
    title: "Permanent Lip Coloring",
    shortDescription: "Wake up with perfectly tinted, defined lips every day.",
    detailedDescription: "Semi-permanent lip tinting enhances your lip color and definition. Wake up with beautifully tinted lips that last 12-18 months with minimal touch-ups.",
    features: ["Custom color", "Enhanced definition", "12-18 month durability", "Touch-up available"],
    price: "Starting from ₹3,000",
    duration: "60 minutes",
    recovery: "3-5 days",
    image: "/placeholder.svg",
  },
  {
    id: "microblading",
    category: "Permanent Makeup",
    title: "Eyebrow Microblading",
    shortDescription: "Natural-looking, fuller brows that last 1-2 years.",
    detailedDescription: "Semi-permanent eyebrow tattooing creates hair-like strokes for full, natural-looking brows. Results last 1-2 years with optional touch-ups.",
    features: ["Hair-like strokes", "Custom design", "1-2 year durability", "Natural appearance"],
    price: "Starting from ₹3,000",
    duration: "90 minutes",
    recovery: "7-10 days",
    image: "/placeholder.svg",
    popular: true,
  },
  {
    id: "bb-glow",
    category: "Permanent Makeup",
    title: "BB Glow Foundation Treatment",
    shortDescription: "Semi-permanent foundation for flawless, glowing skin.",
    detailedDescription: "BB Glow tints your skin with a custom shade that adapts to your undertone. Enjoy flawless coverage and a natural glow for 6-12 months without daily makeup.",
    features: ["Custom shade", "Natural coverage", "6-12 month durability", "No daily makeup needed"],
    price: "Starting from ₹3,000",
    duration: "90 minutes",
    recovery: "3-5 days",
    image: "/placeholder.svg",
  },
  {
    id: "scalp-micropigmentation",
    category: "Permanent Makeup",
    title: "Scalp Micropigmentation",
    shortDescription: "Create the appearance of fuller hair with scalp tattooing.",
    detailedDescription: "Scalp micropigmentation deposits pigment into the scalp to create the illusion of hair density. Perfect for hair loss, thinning hair, or style enhancement.",
    features: ["Hair density illusion", "Permanent tattooing", "Customizable density", "All hair types"],
    price: "Starting from ₹3,000",
    duration: "120 minutes",
    recovery: "7-10 days",
    image: "/placeholder.svg",
  },

  // Facial Plastic Surgery
  {
    id: "chin-augmentation",
    category: "Facial Plastic Surgery",
    title: "Chin Augmentation Surgery",
    shortDescription: "Achieve perfect facial balance with chin reshaping.",
    detailedDescription: "Surgical chin augmentation enhances your facial proportions and profile. Using implants or bone grafting, we create a chin that harmonizes perfectly with your facial features.",
    features: ["Improved facial balance", "Enhanced profile", "Implant or bone graft", "Permanent results"],
    price: "Starting from ₹45,000",
    duration: "45-90 minutes",
    recovery: "1-2 weeks",
    image: "/placeholder.svg",
  },
  {
    id: "jawline-contouring",
    category: "Facial Plastic Surgery",
    title: "Surgical Jawline Definition",
    shortDescription: "Sculpt a strong, defined jawline for enhanced facial structure.",
    detailedDescription: "Surgical jawline contouring reshapes the jaw and chin for a more defined, aesthetic appearance. Creates structure and balance that enhances overall facial aesthetics.",
    features: ["Enhanced definition", "Improved structure", "Permanent contouring", "Facial balance"],
    price: "Starting from ₹50,000",
    duration: "90-120 minutes",
    recovery: "2-3 weeks",
    image: "/placeholder.svg",
    popular: true,
  },
  {
    id: "ear-reshaping",
    category: "Facial Plastic Surgery",
    title: "Ear Reshaping Surgery",
    shortDescription: "Correct protruding or asymmetrical ears for improved confidence.",
    detailedDescription: "Otoplasty surgically corrects ear position and shape. Whether addressing protruding ears or asymmetry, our surgeons create natural-looking, balanced ears.",
    features: ["Protruding ear correction", "Asymmetry fix", "Natural appearance", "Permanent results"],
    price: "Starting from ₹35,000",
    duration: "60-90 minutes",
    recovery: "1-2 weeks",
    image: "/placeholder.svg",
  },
  {
    id: "dimpleplasty",
    category: "Facial Plastic Surgery",
    title: "Dimpleplasty",
    shortDescription: "Create charming, natural-looking dimples with minor surgery.",
    detailedDescription: "Minor surgical procedure creates natural-looking dimples on your cheeks. A quick, simple procedure that adds character and charm to your smile.",
    features: ["Natural dimple creation", "Minor surgery", "Quick procedure", "Permanent dimples"],
    price: "Starting from ₹20,000",
    duration: "30-45 minutes",
    recovery: "3-5 days",
    image: "/placeholder.svg",
  },
  {
    id: "blepharoplasty",
    category: "Facial Plastic Surgery",
    title: "Blepharoplasty (Eye Bag Surgery)",
    shortDescription: "Refresh tired eyes by removing excess skin and fat.",
    detailedDescription: "Eye bag removal surgery eliminates puffiness and excess skin around the eyes. Wake up looking refreshed with brighter, more youthful eyes.",
    features: ["Eye bag removal", "Excess skin removal", "Youthful eyes", "Reduced puffiness"],
    price: "Starting from ₹40,000",
    duration: "60-90 minutes",
    recovery: "1-2 weeks",
    image: "/placeholder.svg",
  },
];

export const categories = [
  "All Services",
  "Advanced Skin Care",
  "Hair Restoration",
  "Permanent Makeup",
  "Facial Plastic Surgery",
];
