export const BRAND_NAME = "Belviso Facial Cosmetic Centre"
export const BRAND_LEGACY = "Belviso"
export const LOGO_SRC = "/logo-mascot.png"
export const LEGACY_LOGO_SRC = "/logo-mascot.png"
export const PHONE = "+91 94470 45560"
export const PHONE_DIAL = "+919447045560"
